apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: demo
  labels:
    app: mysql
    environment: dev
    tier: database
    project: demo
type: Opaque
data:
  MYSQL_USER: Zmxhc2thcGlfdXNlcg==
  MYSQL_PASSWORD: Zmxhc2thcGlfdXNlcl9wYXNzd29yZA==
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
