apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume
  namespace: demo
  labels:
    app: mysql
    environment: dev
    tier: database
    project: demo
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume
  namespace: demo
  labels:
    app: mysql
    environment: dev
    tier: database
    project: demo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
