apiVersion: v1
kind: Service
metadata:
  name: flask-fe
  namespace: demo
  labels:
    environment: dev
    tier: frontend
    project: demo
spec:
  type: NodePort
  selector:
        app: flask-fe
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 5000
      nodePort: 30003
