apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: demo
  labels:
    service: elasticsearch
    tier: logging
spec:
  type: NodePort
  selector:
    component: elasticsearch
  ports:
  - port: 9200
    targetPort: 9200
